var questions = new Array(
    ['As-tu déjà embrassé quelqu’un de notre école ?', 1],
    ['As-tu déjà embrassé quelqu’un des Fks ?', 1],
    ['As-tu déjà été impliqué dans une pipounette ?', 1],
    ['As-tu déjà fourcher dans un lieu insolite (cagibi, escalier,...) -> ou les mettre à part ?', 1],
    ['As-tu déjà fourcher dans les bâtiments de notre école ?', 1],
    ['As-tu déjà choper plus de 2 personnes lors d’un évènement à notre école ?', 1],
    ['T’es-tu déjà réveillé chez quelqu’un que tu ne connais pas ?', 1],
    ['As-tu déjà chopé ton parrain/marraine/filleul(e) ?', 1],
    ['Et as-tu déjà été impliqué dans une fourche avec elle/lui', 1],
    ['Aimes-tu le lait à 37 degrés ?', 1],
    ['As-tu déjà chopé au jeu de la bouteille ?', 1],
    ['As-tu déjà chopé pour rendre jaloux ?', 1],
    ['As-tu déjà pris amende pour tapage ?', 2],
    ['As-tu déjà eu le Covid ?', 2],
    ['As-tu déjà été une incruste de soirée ?', 2],
    ['Tu commandes plus uberEats que t’appelles ta mère ?', 2],
    ['As-tu déjà brailler sur IP ?', 2],
    ['T’es-tu déjà senti changemaker ?', 2],
    ['As-tu déjà eu plus de 20% d’absence en semestre ZOOM ?', 2],
    ['As-tu déjà eu plus de 2 rattrapages en un semestre ?', 2],
    ['As-tu déjà ri du malheur des redoublants ?', 2],
    ['As-tu déjà fait une blague sur l\'échange au Kazakhstan ?', 2],
    ['As-tu déjà laché ta meilleure disquette sur Tinder ', 2],
    ['As-tu déjà utilisé l’excuse de la Pharmacie (pillule du lendemain) en couvre-feu ?', 2],
    ['T’es-tu déjà fait renvoyer d’un cours ZOOM ?', 2],
    ['As-tu déjà demandé un service rémunéré sur IP (Rattrapages, projet de groupe,...) ?', 2],
    ['As-tu déjà été à la Trav ?', 3],
    ['As-tu déjà eu un shot offert par Robert ?', 3],
    ['As-tu déjà écouté plus de 2 fois “bande organisée” dans une même soirée ?', 3],
    ['As-tu déjà fais une Pena Baiona en soirée ?', 3],
    ['Bois-tu plus de 8.6 que d’eau ?', 3],
    ['As-tu déjà vomi d’alcool au cours de cette semaine ?', 3],
    ['As-tu déjà prétendu Black out pour t’éviter un problème ?', 3],
    ['As-tu déjà black out une choppe ?', 3],
    ['As-tu déjà pris le shot au jeu de la pyramide ?', 3],
    ['T’es-tu déjà pissé dessus parce que tu étais trop bourré ?', 3],
    ['As-tu déjà acheté de l’alcool sur UberEats ?', 3],
    ['As-tu déjà cassé quelque chose en étant bourré ?', 3],    
);